# do not edit this file
import os

# url of login page
base_url = "https://accounts.moneycontrol.com/mclogin/?ref=https://www.moneycontrol.com/india/bestportfoliomanager/investment-toolportfolio-investment-dashboard"

# url of stock tab
stock_tab_url = "https://www.moneycontrol.com/portfolio-management/portfolio-investment-dashboard/stock"

# project root path
project_root = os.path.join("..")

# webdriver path
if os.name.lower() == 'nt':
    geckodriver = os.path.join(project_root, "webdrivers", "geckodriver.exe")
elif os.name.lower() == 'posix':
    geckodriver = os.path.join(project_root, "webdrivers", "geckodriver")

# geckodriver log path
geckodriver_log = os.path.join(project_root, "logs", "geckodriver.log")

# spreadsheet path
spreadsheet_path = os.path.join(project_root, "data", "spreadsheet.xlsx")

# backup spreadsheet path
spreadsheet_backup_path = os.path.join(project_root, "data", ".spreadsheet_backup.xlsx")

# data folder path
data_directory_path = os.path.join(project_root, "data")


